language: php

php:
    - 7.1
    - 7.2

cache:
    directories:
        - $HOME/.composer

env:
    matrix:
        - ADDITIONAL_COMPOSER_ARGS=""

matrix:
    fast_finish: true
    include:
        - php: nightly
          env:
            - ADDITIONAL_COMPOSER_ARGS="--ignore-platform-reqs"; PHP_CS_FIXER_IGNORE_ENV=1
    allow_failures:
        - php: nightly

sudo: false

before_install:
    - phpenv config-rm xdebug.ini || return 0

install:
    - travis_retry composer install --no-suggest --no-progress --no-interaction --prefer-dist $ADDITIONAL_COMPOSER_ARGS

script:
- php test.php
- ./vendor/bin/php-cs-fixer fix --dry-run --verbose --diff --diff-format=udiff
